name: Generate Snake Animation 🐍

on:
  schedule:
    - cron: "0 0 * * *"  # Executa todo dia à meia-noite
  push:
    branches:
      - main  # Substitua se sua branch principal for "master"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: LaraKorogix
          outputs: |
            dist/snake.svg

      - name: Commit and Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
